# Определение версии docker compose и начало описания сервисов
version: "3.9"

services:
  db:
    image: postgres:15.2
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: always
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 15

  api:
    image: letimvkocmoc/whats_on_plan:${GITHUB_REF_NAME}-${GITHUB_RUN_ID}
    container_name: api
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      SECRET_KEY: "my_secret_key_value"
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  frontend:
    image: sermalenk/skypro-front:lesson-36
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started

volumes:
  db_data:
