# Generated by Django 4.0.1 on 2023-07-09 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_goalcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего обновления'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goalcomment',
            name='created',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='goalcomment',
            name='updated',
            field=models.DateTimeField(verbose_name='Дата последнего обновления'),
        ),
    ]
